# Generated by Django 4.2.28 on 2026-02-11 09:15
from __future__ import annotations

import uuid

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DONE", "Done"),
                            ("INVALID", "Invalid"),
                            ("IGNORED", "Ignored"),
                            ("FAILED", "Failed"),
                            ("ABORTED", "Aborted"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("retry_after", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "payload",
                    models.JSONField(
                        default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=254)),
                ("endpoint_url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookEventLog",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response_status_code", models.PositiveIntegerField()),
                ("retry_number", models.PositiveIntegerField(default=0)),
                ("response", models.TextField(max_length=4096)),
                (
                    "webhook_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="webhook_toolkit_sender.webhookevent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="webhook_toolkit_sender.webhooksubscription",
            ),
        ),
    ]
